#!/usr/bin/env bash
# this is a simple config for herbstluftwm
hc() {
    herbstclient "$@"
}
export DZEN_HEIGHT=20
export DZEN_BGCOLOR='#101010'
export BORDER_WIDTH=1
export FRAME_GAP=3
export COLOR_THEME='#00bbff'
export COLOR_THEME_NORMAL='#000000'
export TERMINAL='xterm'
export TERMINAL_RUN=$TERMINAL' -e'
export WEB=google-chrome-unstable
export FILE=thunar

hc emit_hook reload

xsetroot -solid $DZEN_BGCOLOR
xrdb -merge ~/.Xresources

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-x close
hc keybind $Mod-e spawn rofi -show run #dmenu_run -h $DZEN_HEIGHT -fn "Noto Sans S Chinese-12" -nb $DZEN_BGCOLOR -nf '#ffffff' -sb $COLOR_THEME -sf black 
hc keybind $Mod-q spawn rofi -show window
hc keybind $Mod-Return spawn $TERMINAL_RUN fish # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-l spawn slimlock

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Alt-Left  shift left
hc keybind $Mod-Alt-Down  shift down
hc keybind $Mod-Alt-Up    shift up
hc keybind $Mod-Alt-Right shift right
hc keybind $Mod-Alt-h     shift left
hc keybind $Mod-Alt-j     shift down
hc keybind $Mod-Alt-k     shift up
hc keybind $Mod-Alt-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       and , split   bottom  0.5 , spawn bash ~/.config/herbstluftwm/tag.sh
hc keybind $Mod-o       and , split   right   0.5 , spawn bash ~/.config/herbstluftwm/tag.sh
# let the current frame explode into subframes
hc keybind $Mod-Control-space and , split explode , spawn bash ~/.config/herbstluftwm/tag.sh

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key"    use_index "$i"
       hc keybind "$Mod-Alt-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Alt-period and , move_index +1 , use_index +1 --skip-visible 
hc keybind $Mod-Alt-comma  and , move_index -1 , use_index -1 --skip-visible

# layouting
hc keybind $Mod-r and , remove , spawn bash ~/.config/herbstluftwm/tag.sh
hc keybind $Mod-p floating toggle
hc keybind $Mod-f fullscreen toggle
#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Volume Control
#hc keybind XF86AudioLowerVolume spawn amixer set Master 5%- unmute
#hc keybind XF86AudioRaiseVolume spawn amixer set Master 5%+ unmute
#hc keybind XF86AudioMute spawn amixer set Master toggle

# Backlight
hc keybind XF86MonBrightnessUp spawn xbacklight + 1 -time 0 -steps 1
hc keybind XF86MonBrightnessDown spawn xbacklight - 1 -time 0 -steps 1

hc keybind Print spawn scrot
hc keybind XF86MyComputer spawn $FILE
hc keybind XF86Calculator spawn galculator
hc keybind XF86HomePage spawn $WEB

hc keybind $Mod-v spawn gvim
hc keybind $Mod-s spawn "emacs"
hc keybind $Mod-n spawn nmcli_dmenu
hc keybind $Mod-t spawn $FILE
hc keybind $Mod-w spawn $WEB

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color $COLOR_THEME
hc set frame_border_normal_color $COLOR_THEME_NORMAL
hc set frame_bg_normal_color $COLOR_THEME_NORMAL
hc set frame_bg_active_color $COLOR_THEME
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap $FRAME_GAP
#hc set frame_normal_opacity 60
#hc set frame_active_opacity 100
bash ~/.config/herbstluftwm/tag.sh

hc attr theme.active.color $COLOR_THEME
hc attr theme.normal.color $COLOR_THEME_NORMAL
hc attr theme.urgent.color $COLOR_THEME
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width $BORDER_WIDTH
hc attr theme.floating.border_width $BORDER_WIDTH
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.floating.active.color $COLOR_THEME
hc attr theme.floating.normal.color $COLOR_THEME_NORMAL
hc attr theme.active.inner_color $COLOR_THEME
hc attr theme.active.outer_color $COLOR_THEME
hc attr theme.background_color $COLOR_THEME_NORMAL

hc set window_gap -$BORDER_WIDTH
hc set frame_padding $BORDER_WIDTH
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on

##hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_SPLASH' manage=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
feh --bg-max /usr/share/backgrounds/starwars6.jpg &
/bin/bash ~/.config/herbstluftwm/startup.sh &
pkill trayer
source ~/.config/init/vars
run=""
while [ -z "$run" ]; do
	sleep 1
	run=$(ps -e | grep dzen)
	echo "$run"
done
trayer --edge top --align right --widthtype request --height $DZEN_HEIGHT --transparent true --alpha 1 --tint 0x`echo $DZEN_BGCOLOR|tail -c 7` --margin 405 &
exit
